import { User } from "@models";
import { Model } from "sequelize-typescript";

const FILE_PATHS = {
  BASE_PATH: "assets",
  PUBLIC: "public",
  AVATAR: "avatar",
  PRIVATE: "private",
  ADMIN: "admin",
  USER: "user",
  LOGO: "logo",
  PROFILE_PICTURE: "profileImg",
  SALE_IMG: "saleImg",
  DOCUMENT: "documents",
  TEMP: "temp",
  EPUB_FILE: "ePubFile",
  AUDIO_SUMMARY: "audioSummary",
  BACKGROUNDIMG: "backgroundImg",
  BANNERIMG: "bannerImg",
  STRIPICON: "stripIcon",
  ADBANNER: "addBannerImage",
  AD: "ad",
  AREAICON: "areaIcon",
  AUDIOFILE: "audioFile",
  NOTIFICATION_IMAGE: "notificationImage",
  NOTIFICATION: "Notification",
  ENTRANCENOTIFICATIONSOUND: "entrancenotificationsound",
  EXITNOTIFICACTIONSOUND: "exitnotificationsound",
  BUSINESS_IMG: "businessImg",
  EXCEL: "excel",
  ICON: "icon",
  INVOICE: "invoice",
  PRODUCTCATEGORYIMAGE: "productCategoryImage",
  PRODUCTIMAGEARABIC: "productImageArabic",
  PRODUCTIMAGEHEBREW: "productImageHebrew",
  POSTCATEGORYIMAGE: "postCategoryImage",
  BANNERIMAGEARABIC: "bannerImageArabic",
  BANNERIMAGEHEBREW: "bannerImageHebrew",
  NIRLAT_TIP_CATEGORY: "nirlatTipCatgory",
  BUSINESSCARDLOGO: "businessCardLogo",
  BUSINESSCARDPROFILE_IMG: "businessCardProfileImg",
  WORK_GALLARY: "workGallary",
  NIRLAT_GIFT_IMG: "nirlatGiftImage",
  NIRLAT_GIFT_IMG_HEBREW: "nirlatGiftImageHebrew",
  NIRLAT_GIFT_IMG_ARABIC: "nirlatGiftImageArabic",
  SCREEN_IMG: "screenImg",
  SCREEN_IMG_HEBREW: "screenImgHebrew",
  SCREEN_IMG_ARABIC: "screenImgArabic",
  INSTRUCTIONAL_CATGORY_IMAGE: "instructionalCatgoryImage",
  INSTRUCTION_VIDEO: "instructionVideo",
  NIRLAT_CONSULTATION: "nirlatConsultation",
  ADMIN_POST_HEBREW_IMG: "adminPostImageHebrew",
  ADMIN_POST_ARABIC_IMG: "adminPostImageArabic",
  ADMIN_POST_HEBREW_VIDEO: "adminPostVideoHebrew",
  ADMIN_POST_ARABIC_VIDEO: "adminPostVideoArabic",
  POSTS: "posts",
  ADMINPOSTS: "adminPosts",
  RECOMMENDATION_GALLARY: "recommendationGallary",
  USER_POST_IMAGE: "userPostImage",
  USER_POST_VIDEO: "userPostVideo",
  USER_POSTS: "userPosts",
  NIRLAT_PROMOTION_ARABIC: "nirlatPromotionArabic",
  NIRLAT_PROMOTION_HEBREW: "nirlatPromotionHebrew",
  NIRLAT_PROMOTION: "nirlatPromotion",
  NIRLAT_PROMOTION_BACKGROUND: "nirlatPromtionBackgroundImage",
  NOTIFICATION_IMAGE_ARABIC: "notificationImageArabic",
  NOTIFICATION_IMAGE_HEBREW: "notificationImageHebrew",
  COMBINATION_TYPE: "combinationType",
  COMBINATION_TYPE_ICON: "combinationTypeIcon",
  IMAGES: "images",
  VIDEOS: "videos",
  BUSINESSCARD: "businessCard",
  COLORFAN_ICON: "colorFanIcon",
  COLORFAN: "colorFan",
  COLORFAN_EXCEL: "colorFanExcel",
  PRICE_OFFER: "priceOfferPdfs",
};

const TEMP_ASSETS = [
  "profileImg",
  "saleImg",
  "logo",
  "fullLogo",
  "thumbnail",
  "form",
  "file",
  "invoice",
  "avatar",
  "ePubFile",
  "audioSummary",
  "organization",
  "backgroundImg",
  "bannerImg",
  "stripIcon",
  "areaIcon",
  "audioFile",
  "csvFile",
  "businessImg",
  "icon",
  "productCategoryImage",
  "productImageArabic",
  "productImageHebrew",
  "postCategoryImage",
  "nirlatTipCategory",
  "businessCardLogo",
  "businessCardProfileImg",
  "workGallary",
  "recommendationGallary",
  "excel",
  "screenImgHebrew",
  "screenImgArabic",
  "instructionalCatgoryImage",
  "instructionVideo",
  "adminPostImageHebrew",
  "adminPostImageArabic",
  "adminPostVideoHebrew",
  "adminPostVideoArabic",
  "nirlatGiftImageHebrew",
  "nirlatGiftImageArabic",
  "userPostImage",
  "userPostVideo",
  "nirlatPromotionArabic",
  "nirlatPromotionHebrew",
  "nirlatPromtionBackgroundImage",
  "notificationImageHebrew",
  "notificationImageArabic",
  "combinationType",
  "combinationTypeIcon",
];

const ACCEPTED_FIELDS = [
  { name: "profilePicture", maxCount: 1 },
  { name: "contract", maxCount: 1 },
  { name: "logo", maxCount: 5 },
  { name: "therapistPhoto", maxCount: 5 },
  { name: "templateImage", maxCount: 1 },
];

type FILE_UPLOAD_FIELDS = (typeof ACCEPTED_FIELDS)[number]["name"];

type UPDATE_MODEL_FIELDS_TYPE<M> = Record<
  FILE_UPLOAD_FIELDS,
  {
    model: M;
    field: string;
    uniqueField: string;
  }
>;

const ALLOWED_MIMETYPES = [
  "image/jpeg",
  "image/png",
  "image/gif",
  "audio/mpeg",
  "video/mp4",
  "audio/mp4",
  "application/pdf",
  "application/msword",
  "text/csv",
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", // .xlsx
  "application/vnd.ms-excel", // .xls
];

export { FILE_PATHS, TEMP_ASSETS, ACCEPTED_FIELDS, ALLOWED_MIMETYPES };
